server {
    listen 8080;
    root   /usr/share/nginx/html;

    server_tokens off;

    gzip            on;
    gzip_vary       on;
    gzip_min_length 1024;
    gzip_proxied    any;
    gzip_types      text/css text/javascript application/javascript application/json image/svg+xml;

    add_header X-Content-Type-Options "nosniff"                                  always;
    add_header X-Frame-Options        "DENY"                                     always;
    add_header Referrer-Policy        "no-referrer"                              always;
    add_header Permissions-Policy     "geolocation=(), microphone=(), camera=()" always;

    location = /healthz {
        access_log   off;
        default_type text/plain;
        return 200 'healthy';
    }

    location ~* \.(?:js|css|woff2?)$ {
        expires 1y;
    }

    location / {
        expires -1;
        try_files $uri $uri/ /index.html;
    }
}
